-- SELECTS THE DATABASE
-- SELECIONA O BANCO DE DADOS
USE BibliotecaDB;

-- CREATE A PROCEDURE TO GET BOOKS BY GEORGE ORWELL
-- CRIA UM PROCEDIMENTO PARA OBTER LIVROS DE GEORGE ORWELL
CREATE PROCEDURE GetLivrosGeorgeOrwell
AS
BEGIN
	SELECT Titulo FROM Livros WHERE AutorID = 5;
END;

-- EXECUTE THE PROCEDURE TO GET BOOKS BY GEORGE ORWELL
-- EXECUTA O PROCEDIMENTO PARA OBTER LIVROS DE GEORGE ORWELL
EXECUTE GetLivrosGeorgeOrwell;

-- CREATE A PROCEDURE TO GET AUTHORS BY NATIONALITY
-- CRIA UM PROCEDIMENTO PARA OBTER AUTORES POR NACIONALIDADE
CREATE PROCEDURE GetAutorPorNacionalidade
	@Nacionalidade VARCHAR(50)
AS
BEGIN
	SELECT Nome FROM Autores WHERE Nacionalidade = @Nacionalidade;
END;

-- EXECUTE THE PROCEDURE TO GET AUTHORS BY NATIONALITY (BRITISH)
-- EXECUTA O PROCEDIMENTO PARA OBTER AUTORES POR NACIONALIDADE (BRITÂNICA)
EXECUTE GetAutorPorNacionalidade @Nacionalidade = 'Britânica';

-- CREATE A PROCEDURE TO COUNT AUTHORS
-- CRIA UM PROCEDIMENTO PARA CONTAR AUTORES
CREATE PROCEDURE ContarAutores 
	@Contagem INT OUTPUT
AS
BEGIN
	SELECT @Contagem = COUNT(*) FROM Autores;
END;

-- DECLARE A VARIABLE, EXECUTE THE PROCEDURE, AND PRINT THE RESULT
-- DECLARA UMA VARIÁVEL, EXECUTA O PROCEDIMENTO E IMPRIME O RESULTADO
DECLARE @Resultado INT;
EXECUTE ContarAutores @Contagem = @Resultado OUTPUT;
PRINT 'Número Total de Autores: ' + CAST(@Resultado AS VARCHAR(10));
